// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_core_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_core_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022002 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_core_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_core_2eproto;
namespace core {
class Bundle;
struct BundleDefaultTypeInternal;
extern BundleDefaultTypeInternal _Bundle_default_instance_;
class Interests;
struct InterestsDefaultTypeInternal;
extern InterestsDefaultTypeInternal _Interests_default_instance_;
}  // namespace core
PROTOBUF_NAMESPACE_OPEN
template <>
::core::Bundle* Arena::CreateMaybeMessage<::core::Bundle>(Arena*);
template <>
::core::Interests* Arena::CreateMaybeMessage<::core::Interests>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace core {
enum Type : int {
  UNSPECIFIED = 0,
  DATA_APD_FULL = 1,
  DATA_APD_PARTIAL = 2,
  DATA_FFT_FULL = 3,
  DATA_FFT_PARTIAL = 4,
  DATA_APD_CVT = 5,
  TIME_APD_CVT = 6,
  DATA_TT_SET = 7,
  DATA_TT_MON = 8,
  CONTROL_LASER = 100,
  CONTROL_VACUUM_PUMP = 101,
  Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool Type_IsValid(int value);
constexpr Type Type_MIN = static_cast<Type>(0);
constexpr Type Type_MAX = static_cast<Type>(101);
constexpr int Type_ARRAYSIZE = 101 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
Type_descriptor();
template <typename T>
const std::string& Type_Name(T value) {
  static_assert(std::is_same<T, Type>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(Type_descriptor(), value);
}
inline bool Type_Parse(absl::string_view name, Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Type>(
      Type_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Bundle final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:core.Bundle) */ {
 public:
  inline Bundle() : Bundle(nullptr) {}
  ~Bundle() override;
  explicit PROTOBUF_CONSTEXPR Bundle(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Bundle(const Bundle& from);
  Bundle(Bundle&& from) noexcept
    : Bundle() {
    *this = ::std::move(from);
  }

  inline Bundle& operator=(const Bundle& from) {
    CopyFrom(from);
    return *this;
  }
  inline Bundle& operator=(Bundle&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Bundle& default_instance() {
    return *internal_default_instance();
  }
  static inline const Bundle* internal_default_instance() {
    return reinterpret_cast<const Bundle*>(
               &_Bundle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Bundle& a, Bundle& b) {
    a.Swap(&b);
  }
  inline void Swap(Bundle* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Bundle* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Bundle* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Bundle>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Bundle& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Bundle& from) {
    Bundle::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Bundle* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "core.Bundle";
  }
  protected:
  explicit Bundle(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 3,
    kTimestampFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // repeated double value = 3;
  int value_size() const;
  private:
  int _internal_value_size() const;

  public:
  void clear_value() ;
  double value(int index) const;
  void set_value(int index, double value);
  void add_value(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& value() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* mutable_value();

  private:
  double _internal_value(int index) const;
  void _internal_add_value(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& _internal_value() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* _internal_mutable_value();

  public:
  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;

  public:
  void clear_timestamp() ;
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();
  // .core.Type type = 2;
  void clear_type() ;
  ::core::Type type() const;
  void set_type(::core::Type value);

  private:
  ::core::Type _internal_type() const;
  void _internal_set_type(::core::Type value);

  public:
  // @@protoc_insertion_point(class_scope:core.Bundle)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<double> value_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};// -------------------------------------------------------------------

class Interests final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:core.Interests) */ {
 public:
  inline Interests() : Interests(nullptr) {}
  ~Interests() override;
  explicit PROTOBUF_CONSTEXPR Interests(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Interests(const Interests& from);
  Interests(Interests&& from) noexcept
    : Interests() {
    *this = ::std::move(from);
  }

  inline Interests& operator=(const Interests& from) {
    CopyFrom(from);
    return *this;
  }
  inline Interests& operator=(Interests&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Interests& default_instance() {
    return *internal_default_instance();
  }
  static inline const Interests* internal_default_instance() {
    return reinterpret_cast<const Interests*>(
               &_Interests_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Interests& a, Interests& b) {
    a.Swap(&b);
  }
  inline void Swap(Interests* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Interests* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Interests* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Interests>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Interests& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Interests& from) {
    Interests::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Interests* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "core.Interests";
  }
  protected:
  explicit Interests(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypesFieldNumber = 1,
  };
  // repeated .core.Type types = 1;
  int types_size() const;
  private:
  int _internal_types_size() const;

  public:
  void clear_types() ;
  public:
  ::core::Type types(int index) const;
  void set_types(int index, ::core::Type value);
  void add_types(::core::Type value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& types() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_types();

  private:
  ::core::Type _internal_types(int index) const;
  void _internal_add_types(::core::Type value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_types();

  public:
  // @@protoc_insertion_point(class_scope:core.Interests)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> types_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _types_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Bundle

// .google.protobuf.Timestamp timestamp = 1;
inline bool Bundle::_internal_has_timestamp() const {
  return this != internal_default_instance() && _impl_.timestamp_ != nullptr;
}
inline bool Bundle::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Bundle::_internal_timestamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Bundle::timestamp() const {
  // @@protoc_insertion_point(field_get:core.Bundle.timestamp)
  return _internal_timestamp();
}
inline void Bundle::unsafe_arena_set_allocated_timestamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = timestamp;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:core.Bundle.timestamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Bundle::release_timestamp() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Bundle::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:core.Bundle.timestamp)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Bundle::_internal_mutable_timestamp() {
  
  if (_impl_.timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.timestamp_ = p;
  }
  return _impl_.timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Bundle::mutable_timestamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:core.Bundle.timestamp)
  return _msg;
}
inline void Bundle::set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp));
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }

  } else {

  }
  _impl_.timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:core.Bundle.timestamp)
}

// .core.Type type = 2;
inline void Bundle::clear_type() {
  _impl_.type_ = 0;
}
inline ::core::Type Bundle::type() const {
  // @@protoc_insertion_point(field_get:core.Bundle.type)
  return _internal_type();
}
inline void Bundle::set_type(::core::Type value) {
   _internal_set_type(value);
  // @@protoc_insertion_point(field_set:core.Bundle.type)
}
inline ::core::Type Bundle::_internal_type() const {
  return static_cast<::core::Type>(_impl_.type_);
}
inline void Bundle::_internal_set_type(::core::Type value) {
  ;
  _impl_.type_ = value;
}

// repeated double value = 3;
inline int Bundle::_internal_value_size() const {
  return _impl_.value_.size();
}
inline int Bundle::value_size() const {
  return _internal_value_size();
}
inline void Bundle::clear_value() {
  _impl_.value_.Clear();
}
inline double Bundle::value(int index) const {
  // @@protoc_insertion_point(field_get:core.Bundle.value)
  return _internal_value(index);
}
inline void Bundle::set_value(int index, double value) {
  _impl_.value_.Set(index, value);
  // @@protoc_insertion_point(field_set:core.Bundle.value)
}
inline void Bundle::add_value(double value) {
  _internal_add_value(value);
  // @@protoc_insertion_point(field_add:core.Bundle.value)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& Bundle::value() const {
  // @@protoc_insertion_point(field_list:core.Bundle.value)
  return _internal_value();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* Bundle::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:core.Bundle.value)
  return _internal_mutable_value();
}

inline double Bundle::_internal_value(int index) const {
  return _impl_.value_.Get(index);
}
inline void Bundle::_internal_add_value(double value) { _impl_.value_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& Bundle::_internal_value() const {
  return _impl_.value_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* Bundle::_internal_mutable_value() {
  return &_impl_.value_;
}

// -------------------------------------------------------------------

// Interests

// repeated .core.Type types = 1;
inline int Interests::_internal_types_size() const {
  return _impl_.types_.size();
}
inline int Interests::types_size() const {
  return _internal_types_size();
}
inline void Interests::clear_types() {
  _impl_.types_.Clear();
}
inline ::core::Type Interests::types(int index) const {
  // @@protoc_insertion_point(field_get:core.Interests.types)
  return _internal_types(index);
}
inline void Interests::set_types(int index, ::core::Type value) {
  _impl_.types_.Set(index, value);
  // @@protoc_insertion_point(field_set:core.Interests.types)
}
inline void Interests::add_types(::core::Type value) {
  _internal_add_types(value);
  // @@protoc_insertion_point(field_add:core.Interests.types)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& Interests::types() const {
  // @@protoc_insertion_point(field_list:core.Interests.types)
  return _impl_.types_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* Interests::mutable_types() {
  // @@protoc_insertion_point(field_mutable_list:core.Interests.types)
  return _internal_mutable_types();
}
inline ::core::Type Interests::_internal_types(int index) const {
  return static_cast<::core::Type>(_impl_.types_.Get(index));
}
inline void Interests::_internal_add_types(::core::Type value) {
  _impl_.types_.Add(value);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* Interests::_internal_mutable_types() {
  return &_impl_.types_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace core


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::core::Type> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::core::Type>() {
  return ::core::Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_core_2eproto_2epb_2eh
