# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x04\x63ore\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n\x06\x42undle\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03\x61pd\x18\x02 \x03(\x05\x12\x0f\n\x07\x61pdtime\x18\x03 \x03(\x01\x12\n\n\x02pa\x18\x04 \x03(\x05\x12\x0b\n\x03\x66\x66t\x18\x05 \x03(\x01\x12\x0c\n\x04\x66req\x18\x06 \x03(\x01\".\n\x03Num\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.core.Type\x12\r\n\x05value\x18\x02 \x01(\x01\".\n\x03\x41rr\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.core.Type\x12\r\n\x05value\x18\x02 \x03(\x01\".\n\x03Str\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.core.Type\x12\r\n\x05value\x18\x02 \x01(\t*\x90\x01\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eTYPE_VOLTAGE_A\x10\x01\x12\x12\n\x0eTYPE_CURRENT_A\x10\x02\x12\x14\n\x10TYPE_HARMONICS_A\x10\x03\x12\x10\n\x0cTYPE_GPS_LAT\x10\x04\x12\x10\n\x0cTYPE_GPS_LON\x10\x05\x12\x10\n\x0cTYPE_GPS_ALT\x10\x06\x32p\n\x06\x42roker\x12\x31\n\x07Publish\x12\x0c.core.Bundle\x1a\x16.google.protobuf.Empty(\x01\x12\x33\n\tSubscribe\x12\x16.google.protobuf.Empty\x1a\x0c.core.Bundle0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPE._serialized_start=353
  _TYPE._serialized_end=497
  _BUNDLE._serialized_start=82
  _BUNDLE._serialized_end=206
  _NUM._serialized_start=208
  _NUM._serialized_end=254
  _ARR._serialized_start=256
  _ARR._serialized_end=302
  _STR._serialized_start=304
  _STR._serialized_end=350
  _BROKER._serialized_start=499
  _BROKER._serialized_end=611
# @@protoc_insertion_point(module_scope)
